### ISSUE TITLE
TypeError when linting `if ... else if ...` statement

### ISSUE THREAD

**Issue by merceyz** [arcanis/eslint-plugin-arca#26]
The following code snippet causes a TypeError when linting
```ts
if (test) {
  test;
} else if (test) {
  test;
}
```

```log
TypeError: Cannot read property 'type' of null
Occurred while linting C:\temp.ts:1
    at getElseKeyword (C:\.yarn\cache\eslint-plugin-arca-npm-0.10.0-eea2ede7c2-90b0a6bab3.zip\node_modules\eslint-plugin-arca\lib\rules\curly.js:59:26)
    at reportUnnecessaryBraceError (C:\.yarn\cache\eslint-plugin-arca-npm-0.10.0-eea2ede7c2-90b0a6bab3.zip\node_modules\eslint-plugin-arca\lib\rules\curly.js:97:48)
    at checkCurly (C:\.yarn\cache\eslint-plugin-arca-npm-0.10.0-eea2ede7c2-90b0a6bab3.zip\node_modules\eslint-plugin-arca\lib\rules\curly.js:138:17)
    at IfStatement (C:\.yarn\cache\eslint-plugin-arca-npm-0.10.0-eea2ede7c2-90b0a6bab3.zip\node_modules\eslint-plugin-arca\lib\rules\curly.js:269:25)
    at C:\.yarn\cache\eslint-npm-6.8.0-d27045f313-d4edbe6958.zip\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\.yarn\cache\eslint-npm-6.8.0-d27045f313-d4edbe6958.zip\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\.yarn\cache\eslint-npm-6.8.0-d27045f313-d4edbe6958.zip\node_modules\eslint\lib\linter\node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (C:\.yarn\cache\eslint-npm-6.8.0-d27045f313-d4edbe6958.zip\node_modules\eslint\lib\linter\node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (C:\.yarn\cache\eslint-npm-6.8.0-d27045f313-d4edbe6958.zip\node_modules\eslint\lib\linter\node-event-generator.js:297:14)
```
Reproduced in https://github.com/yarnpkg/berry/tree/9620239f2f124d2b04246ceb4b9cf42a8fae60c9

**Comment by arcanis** [comment]
Fixed in 0.17
